application/dashboard/forms.py
"""CRUD forms for weights and trips"""
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import (DecimalField,
                     DateField,
                     HiddenField,
                     SubmitField,
                     validators)
from wtforms.validators import (InputRequired,
                                DataRequired,
                                Length,
                                Optional,
                                ValidationError,
                                StopValidation)
import datetime
from datetime import datetime as dt

dateInvalidMsg = f"""Date is not valid."""
dateWrongMsg = f"""Date can't be in the future"""
weightWrongMsg = (f"""That's not a valid weight! """
                  f"""Weight is out of the scale from 20 to 200 kg.""")
fileForbMsg = f"""This file type is forbidden. Use only txt or csv."""


class DataValidation(object):
    """
    Initialises and set a default message
    """
    def __init__(self, message=None):
        super(DataValidation, self).__init__()
        if not message:
            self.message = dateInvalidMsg
    """
    Checks if input date is a valid datetime instance
    and if it is in the future
    """
    def is_valid_date(form, field):
        d1 = field.data
        d2 = dt.now().date()

        if not isinstance(field.data, datetime.date):
            raise StopValidation()
        if d1 > d2:
            raise StopValidation(dateWrongMsg)
    """
    Check if weight is between a valid range of weights
    """
    def is_valid_weight(form, field):
        try:
            weight = float(field.data)
            if weight < 20 or weight > 200:
                raise StopValidation(weightWrongMsg)
        except Exception as e:
            raise StopValidation(weightWrongMsg)


dataValidation = DataValidation


class UploadFileForm(FlaskForm):
    file = FileField('Only admitted txt and csv files',
                     validators=[FileRequired(),
                                 FileAllowed(['txt', 'csv'], fileForbMsg)])
    submit = SubmitField('Upload')

application/dashboard/views.py
"""Routes for dashboard private area."""
import os
import csv
from datetime import datetime
from flask import (Blueprint,
                   render_template,
                   redirect,
                   request,
                   flash,
                   session,
                   url_for)

# from application import login_manager
from application.meta_tags_dict import metaTags

from flask_login import current_user, logout_user
# from application.dashboard.forms import (UploadFileForm,
#                                          DataValidation)
# from werkzeug.utils import secure_filename
# from werkzeug.exceptions import RequestEntityTooLarge

titleText = metaTags['dashboard']['pageTitleDict']
headerText = metaTags['dashboard']['headerDict']

dashboard_bp = Blueprint('dashboard_bp', __name__,
                         template_folder='templates',
                         static_folder='static')


@dashboard_bp.route("/main", methods=['GET', 'POST'])
def main():

    if not current_user.is_authenticated:
        return redirect(url_for('auth_bp.login'))

    # dValidate = DataValidation()
    # fUploadFile = UploadFileForm()

    default = {}
    redirectHoovering = 'main'

    return render_template("dashboard/main.html",
                           titleText=titleText,
                           headerText=headerText,
                           # fUploadFile=fUploadFile,
                           redirectHoovering=redirectHoovering,
                           default=default,)


# @dashboard_bp.route("/upload", methods=['GET', 'POST'])
# def upload():

#     if not current_user.is_authenticated:
#         return redirect(url_for('auth_bp.login'))
    
#     dValidate = DataValidation()
#     fUploadFile = UploadFileForm()

#     redirectHoovering = 'upload'
#     details = ""

#     if request.method == 'POST' and fUploadFile.validate_on_submit():

#         fileName = secure_filename(fUploadFile.file.data.filename)
#         filePath = os.path.join('application/static/uploads', fileName)
#         fUploadFile.file.data.save(filePath)

#         with open(filePath, newline='') as csvfile:
#             fNames = ['weight', 'date']
#             reader = csv.DictReader(csvfile, fieldnames=fNames, delimiter=';')
#             rowNumber = 0
#             errorRow = ""
#             nl = '\n'
            
#             details = f"""Row number {rowNumber}. Reason:"""

#             for row in reader:
#                 rowNumber = rowNumber + 1

#                 try:
#                     weight = float(row['weight'])
#                     dateFromRow = datetime.strptime((row['date']), '%Y/%m/%d')
#                     today = datetime.now()

#                     if float(row['weight']) < 20 or float(row['weight']) > 200:
#                         e = "Weight out of range from 20 to 200 Kg."
#                         errorRow += f"""{details} {e}{nl}"""

#                     if today < dateFromRow:
#                         e = "Date can't be in the future."
#                         errorRow += f"""{details} {e}{nl}"""

#                 except Exception as e:
#                     errorRow += f"""{details} {e}{nl}"""

#             if errorRow != "":
#                 errorMsg = f"""File hasn't been proccessed!{nl}""" \
#                             f"""Couldn't save new data.{nl}""" \
#                             f"""{errorRow}"""

#                 flash(errorMsg, 'error')
#                 return redirect(url_for('dashboard_bp.upload'))

#             # if all imported data is correct, save it to the db
#             with open(filePath, newline='') as csvfile:
#                 fNames = ['weight', 'date']
#                 reader = csv.DictReader(
#                     csvfile, fieldnames=fNames, delimiter=';')

#                 for row in reader:
#                     weightFromRow = float(row['weight'])
#                     dateFromRow = datetime.strptime((row['date']), '%Y/%m/%d')
#                     success = insert(current_user, weightFromRow, dateFromRow)

#                     if not success:
#                         details = "{{ weightFromRow }} ; {{ dateFromRow }}"
#                         flash('Something went wrong with data {{ details }}',
#                               'error')
#                         return redirect(url_for('dashboard_bp.upload'))

#             flash('File uploaded successfully!', 'message')
#             return redirect(url_for('dashboard_bp.upload'))

#     return render_template("dashboard/main.html",
#                            titleText=titleText,
#                            headerText=headerText,
#                            fUploadFile=fUploadFile,
#                            redirectHoovering=redirectHoovering)

application/dashboard/templates/add-weight.html
<h2>Add new weight record</h2>
<form action="{{ url_for('.dashboard') }}" class="margin-top-form" method="POST">
  {{ fAddWeight.csrf_token }}
  
  {{ fAddWeight.weightId(value=default.id) }}

  <div class="form-group">
    {{ fAddWeight.weight.label }}
    {{ fAddWeight.weight(class='form-control', placeholder='0.000', value=default.weight) }}
  </div>

  <div class="form-group">
    {{ fAddWeight.weightDate.label }}
    {{ fAddWeight.weightDate(class='form-control', placeholder='2000-01-01', value=default.date) }}
  </div>

  {{ fAddWeight.submit(class='btn btn-default') }}

</form>

<div class="margin-top-form">
  <p><a href="{{ url_for('.upload') }}" class="font-weight-bold">Upload a file instead.</a></p>
</div>


{% if fAddWeight.weight.errors or fAddWeight.weightDate.errors %}
  {% set errors = fAddWeight.weight.errors if fAddWeight.weight.errors else fAddWeight.weightDate.errors %}
  
  <div class="hoovering">
    <a href="{{ redirectHoovering | safe}}" class="close" >X</a>
    {% for error in errors|unique %}
      <h5>{{ error }}</h5>
    {% endfor %}
  </div>

{% endif %}

application/dashboard/templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
  <div class="row">
    <div class="col-xs-12 col-md-12">
      <h2>{% block headerText %}{{ current_user.name | safe }}, {{ headerText | safe }}{% endblock %}</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-4">
      <h2>Side menu</h2>

      <form action="{{ url_for('auth_bp.logout') }}" method="POST">
        <button type="submit" class="btn btn-default">logout</button>
      </form>

    </div>
    <div class="col-xs-12 col-md-4">
      <h2>My stats</h2>
      {% include "list-weights.html" ignore missing with context %}

    </div>
    <div class="col-xs-12 col-md-4">
      
      {% if fUploadFile %}
        {% include "upload-file.html" ignore missing with context %}
      {% else %}
        {% include "add-weight.html" ignore missing with context %}
      {% endif %}

    </div>
  </div>

{% endblock %}

application/dashboard/templates/dashboard/main.html
{% extends "layout.html" %}

{% block body %}
<div class="row">
    <div class="col-xs-12 col-md-12">
      <h3 class="pull-right">{% block headerText %}{{ current_user.name | safe }}, {{ headerText | safe }}{% endblock %}</h3>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-md-2">
        <h1>Settings</h1>
        {% include "./dashboard/menu-dashboard.html" %}
    </div>

    <div class="col-xs-12 col-md-10">
        <div class="col-xs-12 col-md-8 border-one">
            {% include "dashboard/personal-details.html" ignore missing with context %}
        </div>
        <div class="col-xs-12 col-md-4 border-one">
            {% include "dashboard/membership.html" ignore missing with context %}
        </div>       
    </div>
</div>

{% endblock %}

application/dashboard/templates/dashboard/membership.html
<div>
    <p>Member since</p>
    <p><a href="">Update details</a></p>
    <p><a href="">Close account</a></p>
    <p>Stats</p>
</div>

application/dashboard/templates/dashboard/menu-dashboard.html
{% block menu_dashboard %}
<nav>
    <ul class="nav nav-pills nav-stacked">                
        <li><a href="{{ url_for('weight_bp.main') }}" class="btn btn-default" title="">Weights</a></li>
        <li><a href="{{ url_for('trip_bp.main') }}" class="btn btn-default" title="">Trips</a></li>
        <li><a href="{{ url_for('dashboard_bp.main') }}" class="btn btn-default" title="">Settings</a></li>
        <li><a href="{{ url_for('auth_bp.logout') }}" class="btn btn-default" title="">Logout</a></li>
    </ul>
</nav>
{% endblock %}

application/dashboard/templates/dashboard/personal-details.html
<div>
    <ul>
        <li>Name</li>
        <li>Email</li>
        <li>Password</li>
        <li>Location</li>
        <li>Favourite Airport</li>
        <li>Age</li>
        <li>Weight in</li>
        <li>Height in</li>
        <li>Notifications allowed</li>
    </ul>
</div>

application/dashboard/templates/list-weights.html
<h3>List of weights</h3>
<div class="weight-list">
    {{ fDeleteWeight.csrf_token }}
    <ul>
      {% if weights %}
        {% for w in weights %}
          <li>
            {{ fEditWeight.csrf_token }}
            <form action="{{ url_for('.editWeight') }}" class="crud-form" method="POST">
              {{ fEditWeight.weightId(value=w.id) }}
              {{ fEditWeight.submit(class='btn btn-default') }}   
            </form> 
            {{ fDeleteWeight.csrf_token }}           
            <form action="{{ url_for('.deleteWeight') }}" class="crud-form" method="POST">
              {{ fDeleteWeight.weightId(value=w.id) }}
              {{ fDeleteWeight.submit(class='btn btn-default') }}   
            </form>
            <span class="crud-span">{{ w.weight }} Kg on {{ w.weight_date}}</span>
          </li>
          <hr class="row-separated">
        {% endfor %}
      {% endif %}
    </ul>
</div>

application/dashboard/templates/upload-file.html
<h2>Upload your weights</h2>
<form action="{{ url_for('.upload') }}" class="margin-top-form" method="POST" enctype="multipart/form-data">
  {{ fUploadFile.csrf_token }}
  
  <div class="form-group">
    {{ fUploadFile.file.label }}
    {{ fUploadFile.file(class='form-control') }}
  </div>

  {{ fUploadFile.submit(class='btn btn-default') }}

</form>

<div class="margin-top-form">
  <p><a href="{{ url_for('.dashboard') }}" class="font-weight-bold">Record a weight instead.</a></p>
</div>

{% if fUploadFile.file.errors %}
  <div class="hoovering">
    <a href="{{ redirectHoovering | safe}}" class="close" >X</a>
    {% for error in fUploadFile.file.errors %}
    <h5>{{ error }}</h5>
    {% endfor %}
  </div>
{% endif %}