application/trip/views.py
"""Routes for trips data."""
import os
import re
from csv import DictReader
from ast import literal_eval
from datetime import datetime
from flask import (Blueprint,
                   render_template,
                   redirect,
                   request,
                   flash,
                   session,
                   url_for)

from flask_login import current_user
from application.meta_tags_dict import metaTags
from application.models import db, Trip
from application.general_forms import UploadFileForm
from werkzeug.utils import secure_filename

from application.trip.forms import (AddTripForm,
                                    EditTripForm,
                                    DeleteTripForm)

from application.trip.crudTrip import (readOneTrip,
                                       readAllTrips,
                                       insertTrip,
                                       updateTrip,
                                       deleteTrip)

from application.trip.crudAirport import readAirportList, readAirport
from application.trip.graph_trips import tripsPlot

titleText = metaTags['trips']['pageTitleDict']
headerText = metaTags['trips']['headerDict']

trip_bp = Blueprint('trip_bp', __name__,
                    template_folder='templates',
                    static_folder='static')

airportsList = readAirportList()


@trip_bp.route("/main", methods=['GET', 'POST'])
def main():

    if not current_user.is_authenticated:
        return redirect(url_for('auth_bp.login'))

    allTripsList = readAllTrips(current_user)

    fAddTrip = AddTripForm()
    fEditTrip = EditTripForm()
    fDeleteTrip = DeleteTripForm()
    tripsGraph = tripsPlot()

    showGraph = False
    redirectHoovering = 'main'

    # if user tried to add a new trip
    # but the validation failed
    # user's data will come on as part of the url
    if request.method == 'GET' and request.args.get('userForm') is not None :
        
        # use literal_eval to execute user's data string as dict
        # so I can read it easily
        userForm = literal_eval(request.args.get('userForm'))
        redirectHoovering = ''

        fAddTrip = AddTripForm(departure_origin=userForm.get('departure_origin'),
                           departure_destination=userForm.get('departure_destination'),
                           departure_date=datetime.strptime(userForm.get('departure_date'), '%Y-%m-%d') if userForm.get('departure_date') != 'None' else '',
                           return_origin=userForm.get('return_origin'),
                           return_destination=userForm.get('return_destination'),
                           return_date=datetime.strptime(userForm.get('return_date'), '%Y-%m-%d') if userForm.get('return_date') != 'None' else '',
                           passenger_companion=userForm.get('passenger_companion'))

    # show weight graphic if requested by user
    if request.method == 'GET' and request.args.get('graph') == "true":
        showGraph = True

    return render_template("trip/main.html",
                           titleText=titleText,
                           headerText=headerText,
                           trips=allTripsList,
                           airports=dict(airportsList),
                           fAddTrip=fAddTrip,
                           fEditTrip=fEditTrip,
                           fDeleteTrip=fDeleteTrip,
                           showGraph=showGraph,
                           cdn_javascript=tripsGraph[0],
                           bokehScriptComponent=tripsGraph[1],
                           bokehDivComponent=tripsGraph[2],
                           redirectHoovering=redirectHoovering)


@trip_bp.route("/edit", methods=['GET', 'POST'])
def edit():
    
    if not current_user.is_authenticated:
        return redirect(url_for('auth_bp.login'))

    fAddTrip = AddTripForm()
    fAddTrip.errors = set()

    # edit trip requested by user
    if request.method == 'GET' and len(request.args.get('tripId')) > 0:

        editThisTrip = readOneTrip(current_user, int(request.args.get('tripId')))

        fAddTrip = AddTripForm(tripId=editThisTrip.id,
                               departure_origin=editThisTrip.departure_origin,
                               departure_destination=editThisTrip.departure_destination,
                               departure_date=editThisTrip.departure_date,
                               return_origin=editThisTrip.return_origin,
                               return_destination=editThisTrip.return_destination,
                               return_date=editThisTrip.return_date,
                               passenger_companion=editThisTrip.passenger_companion,
                               errors = set())

        fDeleteTrip = DeleteTripForm(formName='deleteIt')

        redirectHoovering = ''

        return render_template("trip/main.html",
                           titleText=titleText,
                           headerText=headerText,
                           editThisTrip=editThisTrip,
                           fAddTrip=fAddTrip,
                           fDeleteTrip=fDeleteTrip,
                           redirectHoovering=redirectHoovering)

    # update trip requested by user
    if fAddTrip.validate_on_submit() and request.method == 'POST':
        
        success = updateTrip(fAddTrip)        

        if not success:
            flash(f'''Couldn\'t add trip with id { fAddTrip.tripId.data }, sorry''',
                  'error')
            return redirect(url_for('trip_bp.edit'))

    # if there are failures in the form validation
    else:
        count = 0
        for i in fAddTrip.errors:
            if count == 0:
                flash('Warning: ', 'error')
            if count > 0:
                i = f''', and {i.lower()}'''
            flash(i, 'error')
            count += 1

        return redirect(url_for('trip_bp.edit',
                                tripId=fAddTrip.tripId.data))

    flash('Trip added successfully!', 'message')
    
    return redirect(url_for('trip_bp.main'))


@trip_bp.route("/add", methods=['GET', 'POST'])
def add():
    
    if not current_user.is_authenticated:
        return redirect(url_for('auth_bp.login'))

    fAddTrip = AddTripForm()
    fEditTrip = EditTripForm()
    fDeleteTrip = DeleteTripForm()
    allTripsList = readAllTrips(current_user)

    fAddTrip.errors = set()

    redirectHoovering = 'main'

    successflag = ""

    # Validate trip and save submitted form data
    if fAddTrip.validate_on_submit() and request.method == 'POST':

        success = insertTrip(fAddTrip)

        if not success:
            flash('Error saving Trip details!', 'error')
        
        flash('Trip details saved!', 'message')
        return redirect(url_for('trip_bp.main'))

    else:
        # if validation has failed
        # use user data to rebuilt the form
        values = {}
        values['departure_origin'] = f'''{fAddTrip.departure_origin.data}'''
        values['departure_destination'] = f'''{fAddTrip.departure_destination.data}'''
        values['departure_date'] = f'''{fAddTrip.departure_date.data}'''
        values['return_origin'] = f'''{fAddTrip.return_origin.data}'''
        values['return_destination'] = f'''{fAddTrip.return_destination.data}'''
        values['return_date'] = f'''{fAddTrip.return_date.data}'''
        values['passenger_companion'] = f'''{fAddTrip.passenger_companion.data}'''

        count = 0
        for i in fAddTrip.errors:
            if count == 0:
                flash('Warning: ', 'error')
            if count > 0:
                i = f''', and {i.lower()}'''
            flash(i, 'error')
            count += 1

        return redirect(url_for('trip_bp.main', userForm=values))

    return render_template("trip/main.html",
                                   titleText=titleText,
                                   headerText=headerText,
                                   trips=allTripsList,
                                   airports=dict(airportsList),
                                   fAddTrip=fAddTrip,
                                   fEditTrip=fEditTrip,
                                   fDeleteTrip=fDeleteTrip,
                                   redirectHoovering=redirectHoovering,
                                   success=successflag)


@trip_bp.route("/delete", methods=['POST'])
def delete():

    if not current_user.is_authenticated:
        return redirect(url_for('auth_bp.login'))

    fDeleteTrip = DeleteTripForm()

    # delete trip requested by user
    if request.method == 'POST' and fDeleteTrip.tripId.data is not None:
        
        success = deleteTrip(fDeleteTrip.tripId.data)

        if not success:
            flash('Couldn\'t delete trip with id {{ fDeleteTrip.tripId.data }}, sorry',
                  'error')
        else:
            flash('Trip deleted successfully!', 'message')

    return redirect(url_for('trip_bp.main'))


@trip_bp.route("/upload", methods=['GET','POST'])
def upload():

    if not current_user.is_authenticated:
        return redirect(url_for('auth_bp.login'))

    fUploadFile = UploadFileForm()
    fEditTrip = EditTripForm()
    redirectHoovering = 'upload'
    tripsGraph = tripsPlot()

    if request.method == 'POST' and fUploadFile.validate_on_submit():

        fileName = secure_filename(fUploadFile.file.data.filename)
        filePath = os.path.join('application/static/uploads', fileName)
        fUploadFile.file.data.save(filePath)

        fNames = [
            'origin_departure',
            'destination_departure',
            'date_departure',
            'origin_return',
            'destination_return',
            'date_return',
            'passenger_companion']

        with open(filePath, newline='') as csvfile:

            reader = DictReader(csvfile, fieldnames=fNames, delimiter=';')
            rowNum = 0
            errors = []
            _ = 'Error at row'

application/trip/templates/trip/add-trip.html
<form action="{{ url_for('trip_bp.add') }}" class="margin-top-form" method="POST">
    {{ fAddTrip.csrf_token }}
    {{ fAddTrip.tripId }}
    <div class="col-xs-12 col-md-4">
        <h2>Departure</h2>
        <div class="form-group">
            {{ fAddTrip.departure_origin.label }}
            {{ fAddTrip.departure_origin(class='form-control', placeholder='From') }}
            {{ fAddTrip.departure_destination.label }}
            {{ fAddTrip.departure_destination(class='form-control', placeholder='To') }}
            {{ fAddTrip.departure_date.label }}
            {{ fAddTrip.departure_date(class='form-control', placeholder='2000-01-01') }}
        </div>
    </div>
    <div class="col-xs-12 col-md-4">
        <h2>Return</h2>
        <div class="form-group">
            {{ fAddTrip.return_origin.label }}
            {{ fAddTrip.return_origin(class='form-control', placeholder='From') }}
            {{ fAddTrip.return_destination.label }}
            {{ fAddTrip.return_destination(class='form-control', placeholder='To') }}
            {{ fAddTrip.return_date.label }}
            {{ fAddTrip.return_date(class='form-control', placeholder='2000-01-01') }}
        </div>
    </div>
    <div class="col-xs-12 col-md-4">
        <h2>Trip</h2>
        <div class="form-group">
            {{ fAddTrip.passenger_companion.label }}
            {{ fAddTrip.passenger_companion(class='form-control', placeholder='Comma separated names or empty') }}
            {{ fAddTrip.submit(class='btn btn-primary btn-lg margin-top-form pull-right', title='Add new trip') }}
        </div>
    </div>
</form>

application/trip/templates/trip/bokeh-graph.html
{{ bokehDivComponent | safe }}

application/trip/templates/trip/edit-panel.html
<form action="{{ url_for('trip_bp.edit') }}" class="" method="POST">
    {{ fAddTrip.csrf_token }}
    {{ fAddTrip.tripId }}
    <h3>Edit departure details</h3>
    <div class="form-group">
        {{ fAddTrip.departure_origin.label }}
        {{ fAddTrip.departure_origin(class='form-control', placeholder='From') }}
        {{ fAddTrip.departure_destination.label }}
        {{ fAddTrip.departure_destination(class='form-control', placeholder='To') }}
        {{ fAddTrip.departure_date.label }}
        {{ fAddTrip.departure_date(class='form-control', placeholder='2000-01-01') }}
    </div>
    <h3>Edit return details</h3>
    <div class="form-group">
        {{ fAddTrip.return_origin.label }}
        {{ fAddTrip.return_origin(class='form-control', placeholder='From') }}
        {{ fAddTrip.return_destination.label }}
        {{ fAddTrip.return_destination(class='form-control', placeholder='To') }}
        {{ fAddTrip.return_date.label }}
        {{ fAddTrip.return_date(class='form-control', placeholder='2000-01-01') }}
    </div>
    <h3>Edit companions</h3>
    <div class="form-group">
        {{ fAddTrip.passenger_companion.label }}
        {{ fAddTrip.passenger_companion(class='form-control', placeholder='Comma separated names or empty') }}
    </div>
    <br>
    <div class="btn-group pull-right" role="group">
            {{ fAddTrip.tripId(value=fAddTrip.tripId.data) }}
            <button type="submit" class="btn btn-info float-right" title="Update trip">
                <span class="hidden">Confirm</span> <!-- if css disabled show this -->
                <span class="glyphicon glyphicon-ok"></span>
            </button>
        </form>
        <a role="button" class="btn btn-info" href="{{ url_for('trip_bp.main') }}" target="_self" title="Cancel">
            <span class="hidden">Cancel</span> <!-- if css disabled show this -->
            <span class="glyphicon glyphicon-remove"></span>
        </a>
        {{ fDeleteTrip.csrf_token }}    
        <form action="{{ url_for('trip_bp.delete') }}" class="btn-group" method="POST">
            {{ fDeleteTrip.tripId(value=fAddTrip.tripId.data) }}
            <button type="submit" class="btn btn-info float-right" title="Delete this trip.">
                <span class="hidden">Delete</span> <!-- if css disabled show this -->
                <span class="glyphicon glyphicon-trash"></span>
            </button>
        </form>
    </div>

application/trip/templates/trip/list-trips.html
<table>
    <tr><td>
        <div class="col-xs-12 col-md-4">
            <h4><span class="label label-default">DEPARTURE</span></h4>
        </div>
        <div class="col-xs-12 col-md-4">
            <h4><span class="label label-default">RETURN</span></h4>
        </div>
        <div class="col-xs-12 col-md-3">
            <h4><span class="label label-default">COMPANIONS</span></h4>
        </div>
        <div class="col-xs-12 col-md-1">
        </div>
    </td></tr>
    <tr><td>
        {{ fEditTrip.csrf_token }}
        <div class="weight-list">
            <ul>
                {% if trips %}
                    {% set default = 'unknown airport' -%}
                    {% for trip in trips %}
                        <li>
                            <div class="col-xs-12 col-md-4">
                                <div>From {{ airports.get(trip.departure_origin, default) }}</div>
                                <div>To {{ airports.get(trip.departure_destination, default) }}</div>
                                <div class="border-top-sm">Date {{ trip.departure_date.strftime('%Y-%m-%d') }}</div>
                            </div>
                            <div class="col-xs-12 col-md-4">
                                <div>From {{ airports.get(trip.return_origin, default) }}</div>
                                <div>To {{ airports.get(trip.return_destination, default) }}</div>
                                <div class="border-top-sm">Date {{ trip.return_date.strftime('%Y-%m-%d') }}</div>           
                            </div>
                            <div class="col-xs-12 col-md-2">
                                <div>{{ trip.passenger_companion }}</div>
                            </div>
                            <div class="col-xs-12 col-md-2">
                                <div class="col-xs-0 col-md-4">
                                </div>
                                <div class="col-xs-6 col-md-4">
                                    <form action="{{ url_for('trip_bp.edit') }}" method="GET">
                                        {{ fEditTrip.tripId(id=trip.id, value=trip.id) }}
                                        <button type="submit" class="btn btn-info float-right">
                                            <span class="hidden">Edit</span> <!-- if css disabled show this -->
                                            <span class="glyphicon glyphicon-pencil" title="Edit this trip."></span>
                                        </button>
                                    </form>
                                </div>
                                <div class="col-xs-6 col-md-4">
                                    <form action="{{ url_for('trip_bp.delete') }}" method="POST">
                                        {{ fDeleteTrip.tripId(id=trip.id, value=trip.id) }}
                                        <button type="submit" class="btn btn-info float-right">
                                            <span class="hidden">Delete</span> <!-- if css disabled show this -->
                                            <span class="glyphicon glyphicon-trash" title="Delete this trip."></span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </li>
                        <hr class="border-grey">
                    {% endfor %}
                {% endif %}
            </ul>
        </div>
    </td></tr>
</table>

application/trip/templates/trip/main.html
{% extends "./trip/trip-layout.html" %}
{% block body %}
  <div class="row">
    <div class="col-xs-12 col-md-12">
      <h3 class="pull-right">{% block headerText %}{{ current_user.name | safe }}, {{ headerText | safe }}{% endblock %}</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-2">
        <h1>Trips</h1>
        {% include "./dashboard/menu-dashboard.html" %}
    </div>
    <div class="col-xs-12 col-md-10">
        <div class="row">
            <div class="col-xs-12 col-md-4">
            </div>
            <div class="col-xs-12 col-md-8">
                <div class="margin-top-form pull-right">
                    {% if fUploadFile %}
                        <span><a href="{{ url_for('trip_bp.main') }}" class="font-lg">Return to the trips list.</a></span>
                    {% else %}
                        <span><a href="{{ url_for('trip_bp.upload') }}" class="font-lg">Upload a file with your data.</a></span>
                    {% endif %}

                    {% if showGraph %}
                        <span><a href="{{ url_for('trip_bp.main') }}" class="font-lg">Return to the trips list</a></span>
                    {% else %}
                        <span><a href="{{ url_for('trip_bp.main') }}?graph=true" class="font-lg">Show trips graph</a></span>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-md-12">
                {% if editThisTrip %}
                    {% include "trip/edit-panel.html" ignore missing with context %}
                {% elif showGraph %}
                    {% include "trip/trips-graph.html" ignore missing with context %}
                    {% include "trip/add-trip.html" ignore missing with context %}
                {% elif fUploadFile %}
                    {% include "trip/upload-file.html" ignore missing with context %}
                {% else %}
                    {% include "trip/list-trips.html" ignore missing with context %}
                    {% include "trip/add-trip.html" ignore missing with context %}
                {% endif %}
            </div>
        </div> 
    </div>
  </div>
{% endblock %}

application/trip/templates/trip/trip-layout.html
{% extends "layout.html" %}

{% block static %}
    <link rel="stylesheet" href="{{ url_for('trip_bp.static', filename='css/trip-style.css') }}">
{% endblock %}

application/trip/templates/trip/trips-graph.html
{{ bokehDivComponent | safe }}

application/trip/templates/trip/upload-file.html
<h2>Upload your trips</h2>
<form action="{{ url_for('trip_bp.upload') }}" class="margin-top-form" method="POST" enctype="multipart/form-data">
    {{ fUploadFile.csrf_token }}
    <div class="form-group">
    {{ fUploadFile.file.label }}
    {{ fUploadFile.file(class='form-control') }}
    </div>
    <button type="submit" class="btn btn-info">
        <span class="hidden">Upload</span> <!-- if css disabled show this -->
        <span class="glyphicon glyphicon-arrow-up" title="Upload your file now"></span>
    </button>
</form>

{% if fUploadFile.file.errors %}
    <div class="hoovering">
        <a href="{{ redirectHoovering | safe}}" class="close" >X</a>
        {% for error in fUploadFile.file.errors %}
        <h5>{{ error }}</h5>
        {% endfor %}
    </div>
{% endif %}