application/weight/views.py
"""Routes for weights data."""
import os
import csv
from datetime import datetime
from flask import (Blueprint,
                   render_template,
                   redirect,
                   request,
                   flash,
                   session,
                   url_for)
from flask_login import current_user
from application.weight.forms import (AddWeightForm,
                                      DeleteWeightForm,
                                      EditWeightForm,
                                      DataValidation)

from application.general_forms import UploadFileForm
from werkzeug.utils import secure_filename

from application.weight.crudWeight import (read,
                                           insert,
                                           delete,
                                           edit,
                                           update)
from application.weight.formatWeight import formatW
from application.weight.graph_weight import graphWeights
from application.meta_tags_dict import metaTags

weight_bp = Blueprint('weight_bp', __name__,
                      template_folder='templates',
                      static_folder='static')

titleText = metaTags['weights']['pageTitleDict']
headerText = metaTags['weights']['headerDict']


@weight_bp.route("/main", methods=['GET', 'POST'])
def main():

    if not current_user.is_authenticated:
        return redirect(url_for('auth_bp.login'))
    
    fAddWeight = AddWeightForm()
    fDeleteWeight = DeleteWeightForm()
    fEditWeight = EditWeightForm()
    weights = read(current_user)
    
    fUploadFile = None
    graph = ["","",""]
    graphFlag = 0

    redirectHoovering = 'main'
    default = {}

    # show weight graphic if requested by user
    if request.method == 'GET' and request.args.get('graph') == "true":
        graph = graphWeights()
        graphFlag = 1

    # show upload form if requested by user
    if request.method == 'GET' and request.args.get('uploadForm') == "show":
        fUploadFile = UploadFileForm()

    # edit a weight record if requested by user
    if request.method == 'GET' and request.args.get('id'):
        weightId = request.args.get('id')
        editThis = edit(weightId)
        default = {'id': weightId,
                   'weight': editThis.weight,
                   'date': datetime.date(editThis.weight_date)}

    # update or insert a record
    if fAddWeight.validate_on_submit() and request.method == 'POST':
        
        # if posted form contains a weightId, it is an update
        if fAddWeight.weightId.data:

            success = update(
                fAddWeight.weightId.data,
                fAddWeight.weight.data,
                fAddWeight.weightDate.data)

            if not success:
                flash('Couldn\'t update this weight, sorry', 'error')
                return redirect(url_for('weight_bp.main'))

            flash('Weight updated successfully!', 'message')
            return redirect(url_for('weight_bp.main'))

        # else insert a new record
        success = insert(current_user,
                         fAddWeight.weight.data,
                         fAddWeight.weightDate.data)

        if not success:
            flash('Couldn\'t save new weight, sorry', 'error')
            return redirect(url_for('weight_bp.main'))

        flash('Weight recorded successfully!', 'message')
        return redirect(url_for('weight_bp.main'))

    return render_template("weight/main.html",
                           titleText=titleText,
                           headerText=headerText,
                           fAddWeight=fAddWeight,
                           fDeleteWeight=fDeleteWeight,
                           fEditWeight=fEditWeight,
                           fUploadFile=fUploadFile,
                           weights=formatW(weights),
                           showGraph=graphFlag,
                           cdn_javascript=graph[0],
                           bokehScriptComponent=graph[1],
                           bokehDivComponent=graph[2],
                           redirectHoovering=redirectHoovering,
                           default=default)


@weight_bp.route("/edit", methods=['POST'])
def editWeight():

    if not current_user.is_authenticated:
        return redirect(url_for('auth_bp.login'))

    fEditWeight = EditWeightForm()

    if fEditWeight and request.method == 'POST':

        editThis = edit(fEditWeight.weightId.data)

        return redirect(url_for('weight_bp.main',
                                id=fEditWeight.weightId.data,))

    return redirect(url_for('weight_bp.main'))


@weight_bp.route("/delete", methods=['POST'])
def deleteWeight():

    if not current_user.is_authenticated:
        return redirect(url_for('auth_bp.login'))

    fDeleteWeight = DeleteWeightForm()

    if fDeleteWeight and request.method == 'POST':
        success = delete(fDeleteWeight.weightId.data)

        if not success:
            details = "{{ fDeleteWeight.weightId.data }}"
            flash('Couldn\'t delete weight with id {{ details }}, sorry',
                  'error')
        else:
            flash('Weight deleted successfully!', 'message')

    return redirect(url_for('weight_bp.main'))


@weight_bp.route("/upload", methods=['GET', 'POST'])
def upload():

    if not current_user.is_authenticated:
        return redirect(url_for('auth_bp.login'))

    fUploadFile = UploadFileForm()

    redirectHoovering = 'upload'
    details = ""
    uploadForm = ''

    if request.method == 'POST' and fUploadFile.validate_on_submit():

        fileName = secure_filename(fUploadFile.file.data.filename)
        filePath = os.path.join('application/static/uploads', fileName)
        fUploadFile.file.data.save(filePath)

        with open(filePath, newline='') as csvfile:
            fNames = ['weight', 'date']
            reader = csv.DictReader(csvfile, fieldnames=fNames, delimiter=';')
            rowNumber = 0
            errorRow = ""
            nl = '\n'
            
            details = f"""Row number {rowNumber}. Reason:"""

            for row in reader:
                rowNumber = rowNumber + 1

                try:
                    weight = float(row['weight'])
                    dateFromRow = datetime.strptime((row['date']), '%Y/%m/%d')
                    today = datetime.now()

                    if float(row['weight']) < 20 or float(row['weight']) > 200:
                        e = "Weight out of range from 20 to 200 Kg."
                        errorRow += f"""{details} {e}{nl}"""

                    if today < dateFromRow:
                        e = "Date can't be in the future."
                        errorRow += f"""{details} {e}{nl}"""

                except Exception as e:
                    errorRow += f"""{details} {e}{nl}"""

            if errorRow != "":
                errorMsg = f"""File hasn't been proccessed!{nl}""" \
                            f"""Couldn't save new data.{nl}""" \
                            f"""{errorRow}"""

                flash(errorMsg, 'error')
                return redirect(url_for('weight_bp.upload'))

            # if all imported data is correct, save it to the db
            with open(filePath, newline='') as csvfile:
                fNames = ['weight', 'date']
                reader = csv.DictReader(
                    csvfile, fieldnames=fNames, delimiter=';')

                for row in reader:
                    weightFromRow = float(row['weight'])
                    dateFromRow = datetime.strptime((row['date']), '%Y/%m/%d')
                    success = insert(current_user, weightFromRow, dateFromRow)

                    if not success:
                        details = "{{ weightFromRow }} ; {{ dateFromRow }}"
                        flash('Something went wrong with data {{ details }}',
                              'error')
                        return redirect(url_for('weight_bp.upload'))

            flash('File uploaded successfully!', 'message')
            return redirect(url_for('weight_bp.upload'))

    return redirect(url_for('weight_bp.main', uploadForm='show'))
    # return render_template("weight/main.html",
    #                        titleText=titleText,
    #                        headerText=headerText,
    #                        fUploadFile=fUploadFile,
    #                        redirectHoovering=redirectHoovering)

application/weight/templates/weight/add-weight.html
<h2>Add a new weight</h2>
<form action="{{ url_for('weight_bp.main') }}" class="margin-top-form" method="POST">
  {{ fAddWeight.csrf_token }}
  
  {{ fAddWeight.weightId(value=default.id) }}

  <div class="form-group">
    {{ fAddWeight.weight.label(class='pull-right') }}
    {{ fAddWeight.weight(class='form-control', placeholder='0.000', value=default.weight) }}
  </div>

  <div class="form-group">
    {{ fAddWeight.weightDate.label(class='pull-right') }}
    {{ fAddWeight.weightDate(class='form-control', placeholder='2000-01-01', value=default.date) }}
  </div>

    <a role="button" class="btn btn-info pull-right" href="{{ url_for('weight_bp.main') }}" target="_self" title="Cancel">
        <span class="hidden">Cancel</span> <!-- if css disabled show this -->
        <span class="glyphicon glyphicon-remove"></span>
    </a>

    <button type="submit" class="btn btn-info pull-right">
        <span class="hidden">Save</span> <!-- if css disabled show this -->
        <span class="glyphicon glyphicon-ok" title="Save new weight"></span>
    </button>

</form>

{% if fAddWeight.weight.errors or fAddWeight.weightDate.errors %}
  {% set errors = fAddWeight.weight.errors if fAddWeight.weight.errors else fAddWeight.weightDate.errors %}
  
  <div class="hoovering">
    <a href="{{ redirectHoovering | safe}}" class="close" title="Close">X</a>
    {% for error in errors|unique %}
      <h5>{{ error }}</h5>
    {% endfor %}
  </div>

{% endif %}

application/weight/templates/weight/list-weights.html
<table>
    <tr><td>
        <div class="col-md-4 hidden-sm hidden-xs">
        </div>
        <div class="col-md-4 hidden-sm hidden-xs">
            <h4><span class="label label-default">WEIGHT</span></h4>
        </div>
        <div class="col-md-4 hidden-sm hidden-xs">
            <h4><span class="label label-default">DATE</span></h4>
        </div>
    </td></tr>
    <tr><td>
        <div class="hidden-xl hidden-lg hidden-md col-sm-12 col-xs-12">
            <h5><span class="label label-default">WEIGHT</span>

            <span class="label label-default crud-span">DATE</span></h5>
        </div>
        <div class="weight-list">
            {{ fDeleteWeight.csrf_token }}
            <ul>
              {% if weights %}
                {% for w in weights %}
                  <li>
                    <div class="col-xs-2 col-sm-4 col-md-4 col-lg-4 col-xl-4">
                        {{ fEditWeight.csrf_token }}
                        <form action="{{ url_for('weight_bp.editWeight') }}" class="crud-form" method="POST">
                            {{ fEditWeight.weightId(value=w.id) }}
                            <button type="submit" class="btn btn-info float-right">
                                <span class="hidden">Edit</span> <!-- if css disabled show this -->
                                <span class="glyphicon glyphicon-pencil" title="Edit this weight."></span>
                            </button>
                        </form>
                        {{ fDeleteWeight.csrf_token }}           
                        <form action="{{ url_for('weight_bp.deleteWeight') }}" class="crud-form" method="POST">
                            {{ fDeleteWeight.weightId(value=w.id) }}
                            <button type="submit" class="btn btn-info float-right">
                                <span class="hidden">Delete</span> <!-- if css disabled show this -->
                                <span class="glyphicon glyphicon-trash" title="Delete this weight."></span>
                            </button>
                        </form>
                    </div>
                    <div class="col-xs-5 col-sm-4 col-md-4 col-lg-4 col-xl-4">
                        <h4>{{ w.weight }} Kg</h4>
                    </div>
                    <div class="col-xs-5 col-sm-4 col-md-4 col-lg-4 col-xl-4">
                        <h4>{{ w.weight_date}}</h4>
                    </div>
                  </li>
                  <hr class="border-top-sm">
                {% endfor %}
              {% endif %}
            </ul>
        </div>
    </td></tr>    
</table>

application/weight/templates/weight/main.html
{% extends "./weight/weight-layout.html" %}
{% block body %}
  <div class="row">
    <div class="col-xs-12 col-md-12">
      <h3 class="pull-right">{% block headerText %}{{ current_user.name | safe }}, {{ headerText | safe }}{% endblock %}</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-2">
        <h1>Weights</h1>
        {% include "./dashboard/menu-dashboard.html" %}
    </div>
    <div class="col-xs-12 col-md-10">
        <div class="col-xs-12 col-md-8 border-one">
            {% if showGraph %}
                {% include "weight/weights-graph.html" ignore missing with context %}
            {% else %}
                {% include "weight/list-weights.html" ignore missing with context %}
            {% endif %}
        </div>
        <div class="col-xs-12 col-md-4 border-one">

            {% if fUploadFile %}
                {% include "weight/upload-file.html" ignore missing with context %}
            {% else %}
                {% include "weight/add-weight.html" ignore missing with context %}
            {% endif %}

            <div class="margin-top-form pull-right">
                {% if showGraph and not(fUploadFile) %}
                    <a href="{{ url_for('weight_bp.main') }}" method="GET" class="font-lg pull-right">Return to the weight list</a>
                    <a href="{{ url_for('weight_bp.main') }}?graph=true&uploadForm=show" class="font-lg pull-right">Upload a file with your data</a>
                {% elif showGraph and fUploadFile %}
                    <a href="{{ url_for('weight_bp.main') }}?uploadForm=show" method="GET" class="font-lg pull-right">Return to the weight list</a>
                    <a href="{{ url_for('weight_bp.main') }}?graph=true" class="font-lg pull-right">Add a new weight</a>
                {% elif not (showGraph) and fUploadFile %}
                    <a href="{{ url_for('weight_bp.main') }}?graph=true&uploadForm=show" method="GET" class="font-lg pull-right">Show weights graph</a>
                    <a href="{{ url_for('weight_bp.main') }}" class="font-lg pull-right">Add a new weight</a>
                {% else %}
                    <a href="{{ url_for('weight_bp.main') }}?graph=true" method="GET" class="font-lg pull-right">Show weights graph</a>
                    <a href="{{ url_for('weight_bp.main') }}?uploadForm=show" class="font-lg pull-right">Upload a file with your data</a>
                {% endif %}
            </div>
        </div>      
    </div>
  </div>
{% endblock %}

application/weight/templates/weight/upload-file.html
<h2>Upload your weights</h2>
<form action="{{ url_for('weight_bp.upload') }}" class="margin-top-form" method="POST" enctype="multipart/form-data">
    {{ fUploadFile.csrf_token }}
    <div class="form-group">
    {{ fUploadFile.file.label(class='pull-right') }}
    {{ fUploadFile.file(class='form-control') }}
    </div>
    <button type="submit" class="btn btn-info pull-right">
        <span class="hidden">Upload</span> <!-- if css disabled show this -->
        <span class="glyphicon glyphicon-arrow-up" title="Upload your file now"></span>
    </button>
</form>

{% if fUploadFile.file.errors %}
  <div class="hoovering">
    <a href="{{ redirectHoovering | safe}}" class="close" >X</a>
    {% for error in fUploadFile.file.errors %}
    <h5>{{ error }}</h5>
    {% endfor %}
  </div>
{% endif %}

application/weight/templates/weight/weight-layout.html
{% extends "layout.html" %}

{% block static %}
    <link rel="stylesheet" href="{{ url_for('weight_bp.static', filename='css/weight-style.css') }}">
{% endblock %}

application/weight/templates/weight/weights-graph.html
{{ bokehDivComponent | safe }}